PreCommit:
  EsLint:
    required_executable: 'npm'
    enabled: true
    on_warn: 'fail'
    command: ['npm', 'run', 'lint', '--', '-f', 'compact']

  ScssLint:
    enabled: true
    on_warn: 'fail'

  TrailingWhitespace:
    enabled: true
    on_warn: 'fail'
    include: ['src/**/*.jsx', 'src/**/*.js']
